name: frontend
description: "Oreo Platform Standalone UI Shell & Screen Harness"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  go_router: ^13.2.0
  flutter_animate: ^4.5.0
  skeletonizer: ^1.4.2
  fl_chart: ^0.68.0
  google_fonts: ^6.2.1
  file_picker: ^8.0.0
  speech_to_text: ^7.0.0
  flutter_tts: ^4.0.0
  uuid: ^4.6.0
  flutter_svg: ^2.3.0
  path_drawing: ^1.0.1
  intl: ^0.20.3
  shared_preferences: ^2.5.5
  http: ^1.6.0
  google_sign_in: ^7.2.0
  google_sign_in_web: ^1.1.3
  flutter_markdown: ^0.7.7+1
  youtube_player_iframe: ^6.0.2
  stomp_dart_client: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/mascots/cube_pets/png/
    - assets/mascots/cube_characters/png/
    - assets/logos/google/
    - assets/mascots/
