server:
  port: 8080

spring:
  cache:
    type: simple
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/oreo_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      connection-timeout: 20000

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

oreo:
  jwt:
    secret: ${JWT_SECRET:9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b}
    expiration-ms: 604800000 # 7 days
  auth:
    google-client-id: ${GOOGLE_CLIENT_ID:535291260400-mufpocj4te32evfusavcb5e7ee6250rq.apps.googleusercontent.com}
  llm:
    gemini-api-key: ${GEMINI_API_KEY:AQ.Ab8RN6KoeKf1dQ4MbRZpRySorbKKwbs9j2xGX2soNZHpTjyrHg}
  search:
    google-api-key: ${GOOGLE_SEARCH_API_KEY:dummy-key}
    google-csx-id: ${GOOGLE_CSX_ID:dummy-csx}
  
  youtube:
    api:
      key: ${YOUTUBE_API_KEY:mock-key}

logging:
  level:
    root: INFO
    com.oreo: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG


